name: Update Matches

on:
  workflow_dispatch:
  schedule:
    # سيتم تشغيل السكربت كل 4 ساعات (6 مرات في اليوم) لتوفير الباقة
    - cron: '0 */4 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 firebase-admin pytz apify-client
          
      - name: Run python main.py
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          API_KEY: ${{ secrets.API_KEY }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          PYTHONIOENCODING: 'utf-8'
        run: python main.py
