      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin apify-client pytz requests
          # أو إذا كنت تستخدم ملف متطلبات: pip install -r requirements.txt
          
      - name: Run python main.py
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }} # تأكد من إضافة هذا المتغير في السيكريتس أيضاً
        run: python main.py
